apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: employee-info
  # Other metadata and annotations omitted for brevity.
spec:
  type: service
  owner: itvenkata
  lifecycle: experimental
  providesApis:
    - employee-info
