apiVersion: apps/v1
kind: Deployment
metadata:
  name: chthota-springboot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chthota-springboot
  template:
    metadata:
      labels:
        app: chthota-springboot
    spec:
      containers:
        - name: springboot
          image: chthota/chthota-docker-demo:chthota-docker-demo

          resources:
            requests:
              memory: "128Mi"
              cpu: "512m"
            limits:
              memory: "128Mi"
              cpu: "512m"

          ports:
            - containerPort: 8090

          readinessProbe:
            httpGet:
              path: /health
              port: 8090
            initialDelaySeconds: 15
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8090
            initialDelaySeconds: 15
            periodSeconds: 10

          startupProbe:
            httpGet:
              path: /health
              port: 8090
            failureThreshold: 30
            periodSeconds: 10

          env:
            - name: PORT
              value: "8090"
---
apiVersion: v1
kind: Service
metadata:
  name: chthota-springboot
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8090
  selector:
    app: chthota-springboot